services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    ports:
      - "2345:2345"  # Delve debugger port
    environment:
      - CGO_ENABLED=0
      - GOPATH=/go
      - GOCACHE=/go/cache
    # Enable debugging
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE

volumes:
  go-modules: 